### ISSUE TITLE
我看了你代码只是简单的写了LinearLayout用Adapter的方式添加View，没有复用View

### ISSUE THREAD

**Issue by LuckyJayce** [mcxtzhang/NestFullListView#2]
我看了你代码只是简单的写了LinearLayout用Adapter的方式添加View，没有复用View  

如果当存的是这样的话，RecyclerView的24.0.0后的版本就支持直接RecyclerView嵌套RecyclerView了，不需要做任何处理.内部被嵌套的RecyclerView也是直接添加适配器中所有的项，外部的RecyclerView显示的时候加载显示的项

**Comment by mcxtzhang** [comment]
是这样的，没有复用View，  我在文章里也多次提到了（①） 这种方法已经打破了View的复用机制，只是为了更方便的使用而已，您总结的很对，就是LL加了一个Adapter，让使用上方便一些。另外尽可能的提高刷新时的效率。

你说的这种方法 我现在就试一下，还真不知道，不过我先猜测被嵌套的RecyclerView也不会有复用机制吧？稍后看Log说话 

① 如文中第六节 总结：
六 总结：

其实这种方法，真的称不上优雅，只不过跟别的方法比起来，相对优雅吧。 
在我心中最好的方法就是利用RecyclerView的ItemViewType来解决，可惜由于接口，以及数据结构限制，只能退而求其次。如若有朋友有更好的办法，欢迎交流。 
再次强调一遍~本文的方法只是尽可能的节省刷新时的性能消耗， 
不再每次都无脑removeAllViews()，inflate()，addView()。 
利用通用的ViewHolder，减少刷新时的findViewById()操作。

不管是ListViewForScrollView 还是本文的NestFullListView， 
它们都是在一开始，就把所有的子View统统inflate add bind好了， 
不像ListView，RecyclerView..兄弟们，是子View在屏幕上可见时才创建，添加，数据绑定。

**Comment by mcxtzhang** [comment]
我的Rv版本：compile 'com.android.support:recyclerview-v7:24.2.1'
兄弟 ，我实验了你说的这种方法，有两个问题，
一，**View并没有复用** ，如我所想，所有的View在初始化时就onCreateViewHolder 和 onBindViewHolder了，那些没有出现在屏幕上的View也已经初create & bind 好了。
二，如果是复杂的嵌套，父Rv的Item里有一个Rv，在父Rv的Item多于一屏时，向下滑动会报错，
错误如下： 暂时没有找到问题，稍后我会新开一个分支，如果你有兴趣了解 或者解决办法 麻烦告知
09-24 11:06:30.144 31541-31541/com.mcxtzhang.cstnorecyclelistview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.mcxtzhang.cstnorecyclelistview, PID: 31541
                                                                                    java.lang.NoSuchMethodError: No static method getMatrix(Landroid/view/View;)Landroid/graphics/Matrix; in class Landroid/support/v4/view/ViewCompat; or its super classes (declaration of 'android.support.v4.view.ViewCompat' appears in /data/data/com.mcxtzhang.cstnorecyclelistview/files/instant-run/dex/slice-com.android.support-support-v4-23.4.0_1e62650e7ea034df7b42508881c720631f172dd6-classes.dex)
                                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.getTransformedBoundingBox(RecyclerView.java:8100)
                                                                                        at android.support.v7.widget.OrientationHelper$2.getTransformedEndWithDecoration(OrientationHelper.java:402)
                                                                                        at android.support.v7.widget.LinearLayoutManager.recycleViewsFromStart(LinearLayoutManager.java:1275)
                                                                                        at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1347)
                                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1371)
                                                                                        at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
                                                                                        at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
                                                                                        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4413)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:896)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:698)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:630)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:882)
                                                                                        at android.os.Handler.handleCallback(Handler.java:815)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                        at android.os.Looper.loop(Looper.java:207)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5710)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by LuckyJayce** [comment]
一般这个NoSuchMethodError 是版本不一致导致的，你v4的版本号和recyclerview版本号一样么？

**Comment by mcxtzhang** [comment]
赞，解决了，是的，版本号不一致。可惜View复用问题还是没办法解决，看来这种BT需求暂时还没有很优雅的解法，相关代码已提交 RecyclerViewTest 分支，从log可以看出 在嵌套的Adapter里，onCreateViewHolder()  onBindViewHolder() 是一个瞬间全部执行，和我之前文中提到的现象一样。估计Google是在新版的LayoutManager里适配了相关代码，可惜Google也没有想出复用的办法？
